# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wool and the Gand Blog
email: info@woolandthegang.com
description: > # this means to ignore newlines until "baseurl:"
  Wool and the Gang Knitting Kits for beginners, intermediate and advanced knitters. Buy Wool, Patterns, Yarn, Needles and many more knitting supplies.
baseurl: "www.woolandthegang.com" # the subpath of your site, e.g. /blog
url: "www.woolandthegang.com" # the base hostname & protocol for your site
twitter_username: woolandthegang

# Build settings
markdown: kramdown

gems:
  - jemoji

prose:
  rooturl: '_posts'
  # siteurl: ''
  # relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'img'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "author"
        field:
          element: "select"
          label: "Who are you ?"
          placeholder: "Choose your name"
          options:
            - name: "Jess"
              value: "Jess"
            - name: "Brooke"
              value: "Brooke"
            - name: "Jenni"
              value: "Jenni"
            - name: "Charlotte"
              value: "Charlotte"
      - name: "category"
        field:
          element: "multiselect"
          label: "Add Categories"
          placeholder: "Add Categories (e.g Saturday stitches)"
          alterable: true
